version: '3.4'

x-common-variables: &common-variables
  # Check every TASK_DELAY milliseconds
  TASK_DELAY: 5000
  # Alert inactivity after PERIOD seconds
  PERIOD: 30

services:

  zookeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181
    depends_on:
      - zookeper

  heartbeatfd:
    build:
      context: .
      dockerfile: heartbeatfd/Dockerfile
    ports:
      - "7777:7777"
    restart: always
    environment:
      <<: *common-variables

volumes:
  mystorage:
